name: E2E test

on:
  push:
    branches:
      - develop
      - trunk
  pull_request:
    branches:
      - develop

# Disable permissions for all available scopes by default.
# Any needed permissions should be configured at the job level.
permissions: {}

jobs:
  build:
    uses: ./.github/workflows/build-release-zip.yml
    permissions:
      contents: read

  cypress:
    needs: build
    name: ${{ matrix.core.name }} / ${{ matrix.php.name }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    strategy:
      matrix:
        php:
          - {name: 'PHP 7.4', version: '7.4'}
        core:
          - {name: 'WP stable', version: 'latest'}
          - {name: 'WP minimum', version: 'WordPress/WordPress#6.7'}
          - {name: 'WP trunk', version: 'WordPress/WordPress#master'}

    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Download build zip
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
      with:
        name: ${{ github.event.repository.name }}
        path: ${{ github.event.repository.name }}

    - name: Display structure of downloaded files
      run: ls -R
      working-directory: ${{ github.event.repository.name }}

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      env:
        cache-name: cache-node-modules
      with:
        path: |
          node_modules
          ~/.cache
          ~/.npm
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: npm install

    - name: Composer (optional)
      run: composer install
      continue-on-error: true

    - name: Set the core version and plugins config
      run: ./tests/bin/set-wp-config.js --core=${{ matrix.core.version }} --plugins=./${{ github.event.repository.name }}

    - name: Set up WP environment
      run: npm run env:start

    - name: Test
      run: npm run cypress:run

    - name: Update summary
      if: always()
      run: |
          npx mochawesome-merge ./tests/cypress/reports/*.json -o tests/cypress/reports/mochawesome.json
          rm -rf ./tests/cypress/reports/mochawesome-*.json
          npx mochawesome-json-to-md -p ./tests/cypress/reports/mochawesome.json -o ./tests/cypress/reports/mochawesome.md
          npx mochawesome-report-generator tests/cypress/reports/mochawesome.json -o tests/cypress/reports/
          cat ./tests/cypress/reports/mochawesome.md >> $GITHUB_STEP_SUMMARY

    - name: Make artifacts available
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      if: failure()
      with:
        name: cypress-artifact
        retention-days: 2
        path: |
            ${{ github.workspace }}/tests/cypress/screenshots/
            ${{ github.workspace }}/tests/cypress/videos/
            ${{ github.workspace }}/tests/cypress/logs/
            ${{ github.workspace }}/tests/cypress/reports/
